name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@main
      env:
        HUGO_VERSION: 0.107.0
        TARGET_REPO: NamNguyen-hub/NamNguyen-hub.github.io
        TARGET_BRANCH: main
        TOKEN: ${{ secrets.EXAMPLE_TOKEN }}
        HUGO_ARGS: '-t academic'
        CNAME: namnguyen-hub.github.io